:- module(tutorial, [tutorial/0]).

clearScreen():-
    write('\33\[2J'),
    write('\33\[2J').

tutorial:-
    write('                              __'),nl,
    write('                            .d$$b'),nl,
    write('                          .\' TO$;\\'),nl,
    write('                         /  : TP._;'),nl,
    write('                        / _.;  :Tb|'),nl,
    write('                       /   /   ;j$j'),nl,
    write('                   _.-"       d$$$$'),nl,
    write('                 .\' ..       d$$$$;'),nl,
    write('                /  /P\'      d$$$$P. |\\'),nl,
    write('               /   "      .d$$$P\' |\\^"l'),nl,
    write('             .\'           `T$P^"""""  :'),nl,
    write('         ._.\'      _.\'                ;'),nl,
    write('      `-.-".-\'-\' ._.       _.-"    .-"'),nl,
    write('    `.-" _____  ._              .-"'),nl,
    write('   -(.g$$$$$$$b.              .\''),nl,
    write('     ""^^T$$$P^)            .(:'),nl,
    write('       _/  -"  /.\'         /:/;'),nl,
    write('    ._.\'-\'`-\'  ")/         /;/;'),nl,
    write(' `-.-"..--""   " /         /  ;'),nl,
    write('.-" ..--""        -\'          :'),nl,
    write('..--""--.-"         (\\      .-(\\'),nl,
    write('  ..--""              `-\\(\\/;`\\'),nl,
    write('    _.                      :\\'),nl,
    write('                            ;`-\\'),nl,
    write('                           :\\'),nl,
    write('                           ;\\'),nl,
    write('Como jogar Brachyurus?'), nl,
    write('Avance pela história selecionando uma das opções disponíveis, a fim de sobreviver nessa incrível jornada!'), nl,
    write('Cada alternativa será representada por um número inteiro (1, 2, 3, 4...), basta escolher e digitar no terminal.'), nl,
    write('Além disso, é importante que o número da alternativa esteja acompanhado por um ponto final. Ex: 2.'), nl,
    write('Por fim, pressione enter caso queira retornar ao menu. Boa sorte!'), nl, nl,
    write('1. Fechar Tutorial.'), nl,
    read(_),
    clearScreen().
