tutorial:-
    write('                              __'),nl,
    write('                            .d$$b'),nl,
    write('                          .\' TO$;\\'),nl,
    write('                         /  : TP._;'),nl,
    write('                        / _.;  :Tb|'),nl,
    write('                       /   /   ;j$j'),nl,
    write('                   _.-"       d$$$$'),nl,
    write('                 .\' ..       d$$$$;'),nl,
    write('                /  /P\'      d$$$$P. |\\'),nl,
    write('               /   "      .d$$$P\' |\\^"l'),nl,
    write('             .\'           `T$P^"""""  :'),nl,
    write('         ._.\'      _.\'                ;'),nl,
    write('      `-.-".-\'-\' ._.       _.-"    .-"'),nl,
    write('    `.-" _____  ._              .-"'),nl,
    write('   -(.g$$$$$$$b.              .\''),nl,
    write('     ""^^T$$$P^)            .(:'),nl,
    write('       _/  -"  /.\'         /:/;'),nl,
    write('    ._.\'-\'`-\'  ")/         /;/;'),nl,
    write(' `-.-"..--""   " /         /  ;'),nl,
    write('.-" ..--""        -\'          :'),nl,
    write('..--""--.-"         (\\      .-(\\'),nl,
    write('  ..--""              `-\\(\\/;`\\'),nl,
    write('    _.                      :\\'),nl,
    write('                            ;`-\\'),nl,
    write('                           :\\'),nl,
    write('                           ;\\'),nl.
